import { geminiService } from './geminiService';
import { AIGeneratedCatalog, ServiceResponse } from '../types';

export const catalogService = {
  /**
   * Generates a structured product catalog from artisan input text or transcribed voice.
   */
  async generateProductCatalog(inputDescription: string): Promise<ServiceResponse<AIGeneratedCatalog>> {
    try {
      const prompt = `
You are an expert e-commerce catalog assistant specializing in traditional Indian handicrafts and textiles.
Based on the following artisan description, extract and generate a structured product catalog.

Artisan Input: "${inputDescription}"

Respond ONLY with a valid JSON object matching exactly this schema, with no markdown formatting around it:
{
  "productName": "A catchy, premium name for the product",
  "category": "One of: Textiles, Art & Paintings, Home Decor, Jewelry, Other",
  "material": "Primary materials used",
  "craftType": "The traditional craft technique (e.g., Banarasi Weaving, Terracotta)",
  "englishDescription": "A beautiful, premium 3-sentence description of the product in English",
  "hindiDescription": "A culturally appropriate Hindi translation of the description (in Devanagari script)",
  "keywords": ["array", "of", "5", "SEO", "tags"]
}
`;

      const responseText = await geminiService.generateText(prompt, true);
      
      // The API returns JSON string, safely parse it
      const catalogData = JSON.parse(responseText) as AIGeneratedCatalog;
      
      // Basic validation
      if (!catalogData.productName || !catalogData.englishDescription) {
        throw new Error('Incomplete catalog generated by AI');
      }

      return { success: true, data: catalogData };
    } catch (error: any) {
      console.error('Catalog Generation Error:', error);
      
      return { 
        success: false, 
        error: error.message || 'Failed to generate product catalog.'
      };
    }
  }
};
